openapi: 3.0.0
info:
  title: CS 194 API
  version: 1.0

paths:
  /test:
    get:
      summary: Returns test result for MongoDB query.
      responses:
        '200':
          description: Test value.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
